# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pol/devel/Snake3D

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pol/devel/Snake3D

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pol/devel/Snake3D/CMakeFiles /home/pol/devel/Snake3D/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pol/devel/Snake3D/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Snake3D

# Build rule for target.
Snake3D: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Snake3D
.PHONY : Snake3D

# fast build rule for target.
Snake3D/fast:
	$(MAKE) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/build
.PHONY : Snake3D/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/snake.o: src/snake.cpp.o
.PHONY : src/snake.o

# target to build an object file
src/snake.cpp.o:
	$(MAKE) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/snake.cpp.o
.PHONY : src/snake.cpp.o

src/snake.i: src/snake.cpp.i
.PHONY : src/snake.i

# target to preprocess a source file
src/snake.cpp.i:
	$(MAKE) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/snake.cpp.i
.PHONY : src/snake.cpp.i

src/snake.s: src/snake.cpp.s
.PHONY : src/snake.s

# target to generate assembly for a file
src/snake.cpp.s:
	$(MAKE) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/snake.cpp.s
.PHONY : src/snake.cpp.s

src/texture_manager/bmp.o: src/texture_manager/bmp.cpp.o
.PHONY : src/texture_manager/bmp.o

# target to build an object file
src/texture_manager/bmp.cpp.o:
	$(MAKE) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/texture_manager/bmp.cpp.o
.PHONY : src/texture_manager/bmp.cpp.o

src/texture_manager/bmp.i: src/texture_manager/bmp.cpp.i
.PHONY : src/texture_manager/bmp.i

# target to preprocess a source file
src/texture_manager/bmp.cpp.i:
	$(MAKE) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/texture_manager/bmp.cpp.i
.PHONY : src/texture_manager/bmp.cpp.i

src/texture_manager/bmp.s: src/texture_manager/bmp.cpp.s
.PHONY : src/texture_manager/bmp.s

# target to generate assembly for a file
src/texture_manager/bmp.cpp.s:
	$(MAKE) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/texture_manager/bmp.cpp.s
.PHONY : src/texture_manager/bmp.cpp.s

src/texture_manager/texture.o: src/texture_manager/texture.cpp.o
.PHONY : src/texture_manager/texture.o

# target to build an object file
src/texture_manager/texture.cpp.o:
	$(MAKE) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/texture_manager/texture.cpp.o
.PHONY : src/texture_manager/texture.cpp.o

src/texture_manager/texture.i: src/texture_manager/texture.cpp.i
.PHONY : src/texture_manager/texture.i

# target to preprocess a source file
src/texture_manager/texture.cpp.i:
	$(MAKE) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/texture_manager/texture.cpp.i
.PHONY : src/texture_manager/texture.cpp.i

src/texture_manager/texture.s: src/texture_manager/texture.cpp.s
.PHONY : src/texture_manager/texture.s

# target to generate assembly for a file
src/texture_manager/texture.cpp.s:
	$(MAKE) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/texture_manager/texture.cpp.s
.PHONY : src/texture_manager/texture.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Snake3D"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/snake.o"
	@echo "... src/snake.i"
	@echo "... src/snake.s"
	@echo "... src/texture_manager/bmp.o"
	@echo "... src/texture_manager/bmp.i"
	@echo "... src/texture_manager/bmp.s"
	@echo "... src/texture_manager/texture.o"
	@echo "... src/texture_manager/texture.i"
	@echo "... src/texture_manager/texture.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

